import Header from "@/components/Header";
import "../globals.css";
import { Open_Sans } from "next/font/google";
import Banner from "@/components/Banner";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Shopl Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body suppressHydrationWarning={true} className="max-w-7xl mx-auto">
        <Header />
        <Banner />
        <main>{children}</main>
      </body>
    </html>
  );
}
